name: build and publish

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: test and build
        run: ./gradlew -Pversion="$(date +'%Y%m%d%M')" build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
#  snyk:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Gradle vulnerability check
#        uses: snyk/actions/gradle-jdk17@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#          ORG_GRADLE_PROJECT_githubUser: x-access-token
#          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: --org=teamdigihot --fail-on=all --project-name=hm-rapids-and-rivers-v2
#          command: monitor